# Generated by Django 5.0.6 on 2024-05-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesdb',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='categoriesdb',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='Categories Images'),
        ),
    ]
