# Generated by Django 5.0.6 on 2024-05-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_logindb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('UserEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('UserPassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
