# Generated by Django 5.0.6 on 2024-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ct_username', models.CharField(blank=True, max_length=100, null=True)),
                ('Ct_Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Ct_Quantity', models.IntegerField(blank=True, null=True)),
                ('Ct_Total_Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
