# Generated by Django 5.0.6 on 2024-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Order_State', models.CharField(blank=True, max_length=100, null=True)),
                ('Order_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Order_Number', models.IntegerField(blank=True, null=True)),
                ('Order_Email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
