# Generated by Django 5.0.6 on 2024-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Order_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
